name: CI

on:
  create:
    tags:
      - v*
        
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Setup V environment
          uses: nocturlab/setup-vlang-action@v1.1.2
        - name: Create a Release
          uses: actions/create-release@v1.1.4
          with:
            tag_name: ${{ github.ref }}
            release_name: Release ${{ github.ref }}
            body: New version of Shellbin is out!
            draft: false
            prerelease: false
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
